# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "265e6135cbb5e8634c6fc6cf9dcd9dac"
name = "Feedback Clips"
handle = "feedback-clips"
application_url = "https://workable-vertically-rattler.ngrok-free.app"
embedded = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://workable-vertically-rattler.ngrok-free.app/auth/redirect"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
